# General configuration ---------------------------------------------------------------------
RANDOM_STATE: 42
RUN_ON_DATABRICKS_WORKSPACE: False
env: dev

# Data and schemas
DEV_CATALOG: dev
STAGING_CATALOG: staging
PROD_CATALOG: prod
BRONZE_SCHEMA: bronze
SILVER_SCHEMA: silver
GOLD_SCHEMA: gold
ML_ASSET_SCHEMA: airbnb_listing_ml_assets

# Feature table name
FEATURE_TABLE_NAME: airbnb_price_listing_features

# Experiment name
EXPERIMENT_NAME_FE: /Users/henryhfung4_gmail.com#ext#@henryhfung4gmail.onmicrosoft.com/airbnb_price_listing_fe


# Model configuration ------------------------------------------------------------------------
MODEL_NAME: airbnb_price_listing
TARGET: log_price
ID_COLUMN: id

TEST_SIZE: 0.2

INTEGER_COLUMNS:
  - host_id
  - price
  - minimum_nights
  - number_of_reviews
  - calculated_host_listings_count
  - availability_365

SELECTED_CATEGORICAL_FEATURES:
  - is_manhattan
  - neighbourhood
  - room_type

SELECTED_NUMERIC_FEATURES:
  - minimum_nights
  - latitude
  - longitude
  - estimated_listed_months
  - availability_365
  - number_of_reviews
  - calculated_host_listings_count

SELECTED_TIMESTAMP_FEATURES:
  - last_review

THRESHOLD_NEIGHBOURHOOD: 0.01

# Model parameters
MODEL_PARAMS:
  learning_rate: 0.01
  n_estimators: 400
  max_depth: 7
  num_leaves: 70
